apiVersion: v1
kind: ConfigMap
metadata:
  name: employees-postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: employees
  POSTGRES_USER: employees
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.0 # Sets Image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432  # Exposes container port
          envFrom:
            - configMapRef:
                name: employees-postgres-config
            - secretRef:
                name: employees-postgres-secret
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
